---
title: "feather river redd survey locations clean up"
date: "2024-11-06"
output: 
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tidyverse)
library(lubridate)
library(googleCloudStorageR)
library(ggplot2)
library(scales)
library(dplyr)
library(leaflet)
library(RColorBrewer)
library(viridis)
library(readxl)
library(janitor)
library(sf)
library(openxlsx)
library(readxl)
library(leaflet)
library(readr)
```

This markdown is a continuation of mapping_qc.Rmd. Based on the issues found on that markdown, the issues will be fixed here.

```{r, include=FALSE}
# redd survey points
redd_data <- read.csv("data/archive/all_redd_data.csv")

# surveying sites from gis data map
gdb_path <- "data-raw/shapefiles/b105_redd_survey_locations_maps_2021.gdb"

layers <- st_layers(gdb_path)$name
```


```{r, include=FALSE}
# there are a few data entries that have 0 for either latitude or longitude
# filtering out those lat/long that can't be plotted
redd_data |> 
  filter(latitude == 0 |
         longitude == 0) |>  #checking that they are 47 rows that will be fixed
  glimpse()

data_zero_removed <- redd_data |> 
    filter(latitude != 0, #filtering out those 47 rows
         longitude != 0) |>
  glimpse()
  
# •	2022 – 1 data entry
# •	2020 – 4 data entries 
# •	2019 – 10 data entries
# •	2018 – 6 data entries
# •	2015 – 18 data entries
# •	2014 – 8 data entriesca


# Chris shared the correct lat/long for some of these records, and decided to delete some of the entries
fixed_zeros <- read.csv("data-raw/Faulty_lat_long_records_edits_Chris_111224.csv") |> # csv with Chris' notes
  select(-1) |> 
  mutate(Northing = str_trim(Northing)) |>
  filter(Northing != "Erase this data") |> #erasing the 6 data entries he indicates to delete
  select(-c(latitude, longitude, Northing, Easting, X.1)) |>
  clean_names() |>
  glimpse()

#join fixed zero values, and deleted data entries 
redd_data_fixed_zeros <- data_zero_removed |> 
  bind_rows(fixed_zeros) |> 
  glimpse()

```

```{r, include=FALSE}
# filtering the points that off channel
off_channel_removed <- redd_data_fixed_zeros |>
  filter(
!(
  (location == "lower auditorium" & date == "2014-09-18" & survey_wk == "2-2" & file_number == "66") |
(location == "lower auditorium" & date == "2015-10-29" & survey_wk == "7-3" & file_number == "5") |
(location == "lower auditorium" & date == "2015-10-22" & survey_wk == "6-4" & file_number == "44") |
(location == "top of auditorium" & date == "2015-11-24" & survey_wk == "11-1" & file_number == "44") |
(location == "upper hatchery riffle" & date == "2014-10-22" & survey_wk == "7-2" & file_number == "37") |
(location == "table mountain" & date == "2015-09-22" & survey_wk == "2-2" & file_number == "10") |
(location == "top of auditorium" & date == "2014-10-20" & survey_wk == "7-1" & file_number == "88") |
(location == "top of auditorium" & date == "2014-10-14" & survey_wk == "6-1" & file_number == "84") |
(location == "lower auditorium" & date == "2015-10-19" & survey_wk == "6-1" & file_number == "16") |
(location == "middle auditorium" & date == "2015-10-22" & survey_wk == "6-4" & file_number == "106") |
(location == "upper hatchery" & date == "2015-10-28" & survey_wk == "7-2" & file_number == "17") |
(location == "mid auditorium" & date == "2014-11-13" & survey_wk == "8-2" & file_number == "174") |
(location == "moe's side channel" & date == "2015-10-09" & survey_wk == "4-4" & file_number == "87") |
(location == "moe's side channel" & date == "2015-10-30" & survey_wk == "7-4" & file_number == "87") |
(location == "lower auditorium" & date == "2014-10-01" & survey_wk == "4-2" & file_number == "64") |
(location == "upper hatchery riffle" & date == "2014-10-02" & survey_wk == "4-3" & file_number == "31")
)
)|>
glimpse()

#reding in Chris' file with corrections
fixed_off_channel <- read.csv("data-raw/Off_channel_records_edit_Chris_110524.csv") |> 
  glimpse()

fixed_off_channel <- fixed_off_channel |> 
  clean_names() |> 
  select(-c(latitude, longitude, corrected_utm_easting, corrected_utm_northing, x)) |>
  rename(latitude = "corrected_latitude",
         longitude = "corrected_longitude") |>
  glimpse()

redd_locations_fixed <- off_channel_removed |> 
  bind_rows(fixed_off_channel) |> 
  glimpse()
```


```{r}
leaflet(redd_locations_fixed) |> 
  addTiles() |> 
  addCircleMarkers(
    ~longitude, ~latitude,
    popup = ~paste0("Number of Redds: ", number_redds, "<br>Lat: ", latitude,"<br>Long: ", longitude),
    radius = 2,  # Adjust radius as needed
    color = "red",
    # label = ~as.character(location),
    # labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE)
  )
```

Save clean data
```{r}
write.csv(redd_locations_fixed, "data-raw/redd_observations_clean_locations.csv", row.names = FALSE) # adding this code to bring location names back

write.csv(redd_locations_clean, "data/redd_observations.csv", row.names = FALSE)

redd_locations_clean <- redd_locations_fixed |> 
  select(-c(location, survey_wk, file_number)) |>   #removing unnecessary fields 
  glimpse()

write.csv(redd_locations_clean, "data/redd_observations.csv", row.names = FALSE)
```

```{r}
read.csv("data/redd_observations.csv") |> glimpse()
```


